# Generated by Django 4.1.2 on 2022-11-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0003_uploadshoppingproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadshoppingproducts',
            name='product_image',
            field=models.ImageField(default=1, upload_to='product_images'),
            preserve_default=False,
        ),
    ]
