# Generated by Django 4.1.2 on 2022-11-12 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0004_uploadshoppingproducts_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadshoppingproducts',
            name='product_image',
            field=models.ImageField(null=True, upload_to='product_images'),
        ),
    ]
