# Generated by Django 4.1.3 on 2022-11-28 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0006_uploadvideosmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadvideosmodel',
            name='video',
            field=models.FileField(upload_to='videos'),
        ),
    ]
